### ISSUE TITLE
Order Sync page is blank

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#28] opened 2015-09-10 15:38 UTC
see:

http://ec2-54-157-249-149.compute-1.amazonaws.com/index.php/admin/orders_sync/index/key/742a59da84704b28597071ed978a3a9d/

loads totally blank. i tried wiping the cache, no dice. installed update via modman
`cd ~/apps/magento/htdocs && modman update reverb-magento`

**Comment by skwp** [comment] 2015-09-10 15:39
seeing this in logs
2015-09-10T15:38:04+00:00 ERR (3): Notice: Trying to get property of non-object  in /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Cron/Model/Observer.php on line 67

**Comment by dunagan5887** [comment] 2015-09-10 17:23
I'm trying to find the PHP error log to debug this issue but I'm not finding one; I output phpinfo() and there's no value defined for the PHP error log. Do you have any idea where it is?

Also the cron error looks like cache wasn't actually cleared, but I went in and cleared it manually and this is still occurring. I'll continue to try to debug these issues, but if I could get the path to the PHP error log that would help greatly

**Comment by skwp** [comment] 2015-09-10 17:41
I'm just doing 
`tail -f ~/apps/magento/htdocs/var/log/*`

I am seeing this message in the `system.log`

I did see some debug logs related to order sync so it's possible the cron is working but not the page load

**Comment by dunagan5887** [comment] 2015-09-10 17:47
I'm wondering if these are environmental issues because I'm not seeing any of these errors on my local. I'll check to see if APC or something is causing this.

Also tail -f ~/apps/magento/htdocs/var/log/* will only show Magento specific errors. The blank screen looks like it's being caused by a fatal PHP error. I committed an update on branch issues/github_28 which may circumvent the issue

**Comment by skwp** [comment] 2015-09-10 17:58
I also saw this

2015-09-10T15:55:02+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in /opt/bitnami/apps/magento/htdocs/.modman/reverb-magento/app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval.php on line 34

**Comment by dunagan5887** [comment] 2015-09-10 17:59
At this point it looks like there's a serious issue with the bitnami Magento instance. I placed a debug line in Mage/Cron/Model/Observer.php and Mage::getConfig()->getNode('default/crontab/jobs'); is not returning an object. This basically means that there's an issue with Magento not being able to process any crons. 

I'm not sure how much time you want me to spend debugging this bitnami instance; should I continue digging or move on to the order update sync process?

The commit on branch issues/github_28 addresses the "Warning: Invalid argument supplied for foreach() " issue

**Comment by skwp** [comment] 2015-09-10 18:00
I do need some way to test this. If this is an issue on my instance it may be an issue on other instances as well?

**Comment by skwp** [comment] 2015-09-10 18:01
I updated the instance with your #28 update

**Comment by dunagan5887** [comment] 2015-09-10 18:02
I'm not seeing the issue on my instance. Is there some documentation on the bitnami Magento instance? I'm wondering if there are services working on the server that I'm not aware of

**Comment by skwp** [comment] 2015-09-10 18:03
there are tons of docs but it's probably not worth getting thru all of that https://wiki.bitnami.com/Applications/BitNami_Magento

are you seeing the latest errors with $defaultJobsRoot is not an object

**Comment by dunagan5887** [comment] 2015-09-10 18:04
I placed the "$defaultJobsRoot is not an object" debug line in there to see what was causing the "Trying to get property of non-object in /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Cron/Model/Observer.php" error

**Comment by skwp** [comment] 2015-09-10 18:04
http://blog.belvg.com/magento-certified-developer-exam-setting-up-a-cron-job.html

It seems to indicate we should use "crontab/jobs" not "default/crontab/jobs"

**Comment by skwp** [comment] 2015-09-10 18:05
hipchat might be easier :)

**Comment by dunagan5887** [comment] 2015-09-10 18:05
I'll remove the "$defaultJobsRoot is not an object" line now. 

 Warning: Invalid argument supplied for foreach() in /opt/bitnami/apps/magento/htdocs/.modman/reverb-magento/app/code/community/Reverb/ReverbSync/Helper/Orders/Retrieval.php on line 34

^ This is no longer occurring as of my latest commit

**Comment by dunagan5887** [comment] 2015-09-10 18:05
yes, let's hipchat

**Closed** 2015-09-10 19:23 UTC
Labels: bug
