### ISSUE TITLE
Empty address on order sync V0.9.3

### ISSUE THREAD

**Issue by zztimur** [reverbdotcom/reverb-magento#252] opened 2016-05-12 17:53 UTC
![screen shot 2016-05-12 at 9 09 23 am 2](https://cloud.githubusercontent.com/assets/623922/15224708/7a220582-1840-11e6-9e6b-6bf8bb866e91.png)

**Comment by skwp** [comment] 2016-05-12 18:02
@dunagan5887 could this be caused by the recent changes to addresses on orders

**Comment by skwp** [comment] 2016-05-12 18:02
@zztimur this was an offer so it's possible the address came later. do you have something stuck in update order tasks that maybe didn't process?

**Comment by zztimur** [comment] 2016-05-12 18:26
Not sure yet, I'm off till the end of week, but thought I'd pass the note.
I'll update you if something changes.

On Thu, May 12, 2016 at 1:02 PM, Yan Pritzker <notifications@github.com>
wrote:

> @zztimur <https://github.com/zztimur> this was an offer so it's possible
> the address came later. do you have something stuck in update order tasks
> that maybe didn't process?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/reverbdotcom/reverb-magento/issues/252#issuecomment-218837439>
>



-- 
-- Sent from my iPhone

**Comment by kylecrum** [comment] 2016-05-12 18:32
this is expected behavior for something without an address.

**Comment by joshlew** [comment] 2016-09-28 19:21
I am getting this on orders that have addresses. All orders in fact.
<img width="1143" alt="screen shot 2016-09-28 at 2 58 17 pm" src="https://cloud.githubusercontent.com/assets/5543058/18928652/0536cc64-858f-11e6-9084-0e0252afbab6.png">
![screen_shot_2016-09-28_at_3_20_24_pm](https://cloud.githubusercontent.com/assets/5543058/18928706/3f62804a-858f-11e6-9908-58142b321fc8.jpg)

**Comment by kylecrum** [comment] 2016-09-28 19:34
@joshlew we have a job scheduled with the cron runner that should come through and update the orders. Can you post some cron logs?

**Comment by kylecrum** [comment] 2016-09-28 19:42
@joshlew I just checked the API on our end for your account and it is working as expected. There is something in your magento instance that is preventing saves.

**Comment by joshlew** [comment] 2016-09-28 21:09
What I am seeing in the log is  _the status update for order with magento entity id 4134 to status paid: The Magento order with increment id 000000027 can not be invoiced: The order has already been marked as complete_

**Comment by kylecrum** [comment] 2016-09-28 21:28
@joshlew thanks. We're looking into it.

**Comment by dunagan5887** [comment] 2016-09-28 21:34
Nothing immediately comes to mind which would cause this, are there other third party extensions which deal with Orders on the instance?

**Comment by joshlew** [comment] 2016-09-28 21:36
Yup, an inventory management extension. I am talking with their developers.

Josh Lewis
LittleFishAudio.com
Office: +1 877 442 8346
Mobile: 305 283 4593

**Closed** 2016-10-19 15:08 UTC
